### ISSUE TITLE
Colour with grep

### ISSUE THREAD

**Issue by mikblack** [GenomicsAotearoa/shell-for-bioinformatics#1]
In: 1.UnixShellBasics/README.md

Question about how to preserve colours from grep when piped to less. 

Solution:
```
grep -v "^>" tb1.fasta | grep --color=always -i "[^ATCG]" | less -R
```

**Comment by DininduSenanayake** [comment]
Done. I have added `--color=always` to **Combining pipes and redirection** on `docs/2_unixshellbasics.md`
