### ISSUE TITLE
Section numbering and organisation

### ISSUE THREAD

**Issue by mikblack** [GenomicsAotearoa/shell-for-bioinformatics#4]
The numbering is messed up between sections, and some sections are folders containing a README.md file, whereas others are numbered markdown files in the `workshop_material` folder.

**Comment by DininduSenanayake** [comment]
We are changing the repo structure to facilitate `MkDocs` depolyment. All .md material pages are being moved to `docs/` directory and defined on the `mkdocs.yml` file on parent directory. 

So, we can consider this to be solved but I do need a bit more time with directory `4.UnixDataTools` .i.e. Requires a review before being merged into `docs/2_unixshellbasics.md`
