### ISSUE TITLE
Counting columns

### ISSUE THREAD

**Issue by mikblack** [GenomicsAotearoa/shell-for-bioinformatics#6]
When we were using `cut`, someone asked how you determine how many columns there are.

We came up with:

```
grep -v "^#" Mus_musculus.GRCm38.75_chr1.gtf | head -1 | tr '\t' '\n' | wc -l
```

First do:

```
grep -v "^#" Mus_musculus.GRCm38.75_chr1.gtf | head -1 | tr '\t' '\n' 
```
to show that last column has the format:

```
gene_id "ENSMUSG00000090025"; gene_name "Gm16088"; gene_source "havana"; gene_biotype "pseudogene";
```

which is why this approach:

```
grep -v "^#" Mus_musculus.GRCm38.75_chr1.gtf | head -1 | wc -w
```

doesn't work in this situation (counts the entries separated by spaces as well).

**Comment by DininduSenanayake** [comment]
I have added a "warning" section **Counting the number of columns of a .gtf with grep and wc** to http://127.0.0.1:8000/shell-for-bioinformatics/4_inspectmanipluate/#using-cut-with-column-data-and-formatting-tabular-data-with-column
